name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint and Google's pylintrc
      run: |
        pylint --rcfile .github/workflows/pylintrc --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` | tee pylint.txt
    - name: Upload pylint.txt as artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint report
        path: pylint.txt
